<?xml version="1.0"?>
<package format="2">
  <name>integrator</name>
  <version>0.0.1</version>
  <description>ROS messages and services for Webots UR3 simulation bridge</description>
  <maintainer email="maintainer@example.com">VR-DT-DRL</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>
</package>
